"""Add plant_stage column to users

Revision ID: 40a14f284328
Revises: 63282884d4fa
Create Date: 2025-05-04 16:17:18.811168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a14f284328'
down_revision: Union[str, None] = '63282884d4fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plant_stage', sa.Enum('seed', 'seedling', 'seedling_with_leaves', 'young_tree', 'growing_tree', 'mature_tree', name='plantstageenum'), nullable=False, server_default='seed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plant_stage')
    # ### end Alembic commands ###
