"""log of tasks updated

Revision ID: 58ac33a60de6
Revises: b4a8dccee964
Create Date: 2025-05-05 14:01:55.684816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ac33a60de6'
down_revision: Union[str, None] = 'b4a8dccee964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_task_logs_daily_task_id_fkey', 'user_task_logs', type_='foreignkey')
    op.drop_column('user_task_logs', 'daily_task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_task_logs', sa.Column('daily_task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_task_logs_daily_task_id_fkey', 'user_task_logs', 'daily_tasks', ['daily_task_id'], ['id'])
    # ### end Alembic commands ###
