"""daily-task xp field changed

Revision ID: 7264f0d327e8
Revises: c842ffa147fa
Create Date: 2025-05-04 23:20:05.996315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7264f0d327e8'
down_revision: Union[str, None] = 'c842ffa147fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_tasks', sa.Column('xp_earned', sa.Float(), nullable=True))
    op.drop_column('daily_tasks', 'green_score_estimate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_tasks', sa.Column('green_score_estimate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('daily_tasks', 'xp_earned')
    # ### end Alembic commands ###
