"""fix daily eco-action tasks

Revision ID: c842ffa147fa
Revises: 036342c0564c
Create Date: 2025-05-04 21:26:17.260596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c842ffa147fa'
down_revision: Union[str, None] = '036342c0564c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_tasks', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('eco_actions', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('user_task_logs', sa.Column('daily_task_id', sa.Integer(), nullable=True))
    op.add_column('user_task_logs', sa.Column('eco_action_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_task_logs_task_id_fkey', 'user_task_logs', type_='foreignkey')
    op.create_foreign_key(None, 'user_task_logs', 'daily_tasks', ['daily_task_id'], ['id'])
    op.create_foreign_key(None, 'user_task_logs', 'eco_actions', ['eco_action_id'], ['id'])
    op.drop_column('user_task_logs', 'task_id')
    op.drop_column('users', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_task_logs', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_task_logs', type_='foreignkey')
    op.drop_constraint(None, 'user_task_logs', type_='foreignkey')
    op.create_foreign_key('user_task_logs_task_id_fkey', 'user_task_logs', 'daily_tasks', ['task_id'], ['id'])
    op.drop_column('user_task_logs', 'eco_action_id')
    op.drop_column('user_task_logs', 'daily_task_id')
    op.drop_column('eco_actions', 'title')
    op.drop_column('daily_tasks', 'title')
    # ### end Alembic commands ###
