"""Removed unused tables

Revision ID: dd53690f3d77
Revises: 40a14f284328
Create Date: 2025-05-04 19:34:55.323676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd53690f3d77'
down_revision: Union[str, None] = '40a14f284328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plant_personas_id', table_name='plant_personas')
    op.drop_table('plant_personas')
    op.alter_column('users', 'plant_stage',
               existing_type=postgresql.ENUM('seed', 'seedling', 'seedling_with_leaves', 'young_tree', 'growing_tree', 'mature_tree', name='plantstageenum'),
               nullable=True,
               existing_server_default=sa.text("'seed'::plantstageenum"))
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'plant_stage',
               existing_type=postgresql.ENUM('seed', 'seedling', 'seedling_with_leaves', 'young_tree', 'growing_tree', 'mature_tree', name='plantstageenum'),
               nullable=False,
               existing_server_default=sa.text("'seed'::plantstageenum"))
    op.create_table('plant_personas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mood', postgresql.ENUM('happy', 'sad', 'neutral', name='moodenum'), autoincrement=False, nullable=True),
    sa.Column('motivational_quote', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='plant_personas_pkey')
    )
    op.create_index('ix_plant_personas_id', 'plant_personas', ['id'], unique=False)
    # ### end Alembic commands ###
